package com.weatherpossum.app.presentation

val caribbeanWeatherFacts = listOf(
    "Dominica receives over 300 inches of rainfall a year in its rainforests — making it one of the wettest islands in the Caribbean.",
    "Hurricane David in 1979 was the most devastating storm to ever hit Dominica, causing widespread destruction and loss of life.",
    "The Caribbean hurricane season runs from June 1 to November 30, with peak activity usually in August and September.",
    "The Sargassum seaweed blooms in the Atlantic are influenced by changing ocean temperatures and wind patterns.",
    "The Atlantic warm pool — a huge area of warm water — plays a major role in fueling hurricanes that threaten the Caribbean.",
    "Trade winds help keep many Caribbean islands cooler despite their tropical latitude.",
    "Dominica's volcanic terrain creates its own microclimates, with different weather patterns on opposite sides of the island.",
    "Thunderstorms are common in Dominica's interior, especially in the afternoon due to heat rising off the land.",
    "The smell after rain is called 'petrichor', caused by oils released from plants and soil bacteria.",
    "Rainbow sightings are common in Dominica, especially near waterfalls where mist and sun combine.",
    "Dominica's Layou River can flood suddenly after heavy inland rain, even when it's sunny near the coast.",
    "The Caribbean Sea is generally warmer than the Atlantic, which can influence how storms develop and where they move.",
    "The Morne Trois Pitons area often gets more rain than the coast, due to elevation and cloud trapping by mountains.",
    "Clouds appear white because they scatter all wavelengths of sunlight, but storm clouds are darker because they're thicker.",
    "Hurricanes rotate counterclockwise in the Northern Hemisphere and clockwise in the Southern Hemisphere.",
    "The eye of a hurricane is calm, but surrounded by the most dangerous winds and rain in the eyewall.",
    "Lightning is hotter than the surface of the sun, reaching temperatures over 30,000°C (54,000°F).",
    "Dominica's rivers rise quickly during tropical systems — always avoid crossing fast-moving water.",
    "Some trees in Dominica, like the coconut palm, can withstand strong winds due to their flexible trunks and roots.",
    "The Caribbean experiences more intense rain events due to climate change, with shorter but heavier downpours.",
    "A single cumulus cloud can weigh more than 1 million pounds, yet it floats due to warm rising air.",
    "Dominica is often called the 'Nature Island' partly because of its untouched cloud forests, which are fed by constant moisture.",
    "The color of the sea changes with weather — sunny skies make it turquoise, storms make it look gray or brown due to runoff.",
    "The Atlantic Ocean can produce long, invisible swells, reaching Dominica's coast days before a storm is near.",
    "The 'heat index' or 'feels-like temperature' is higher in humid Caribbean islands, making 32°C feel like 40°C or more.",
    "Fog is simply a cloud near the ground, and it's common in Dominica's highlands early in the morning.",
    "Windward and leeward sides of Caribbean islands have different climates — Dominica's east coast is wetter than the west.",
    "Rain can fall while the sun is shining, leading to the saying 'the devil is beating his wife' in Caribbean folklore.",
    "You can estimate how far lightning is by counting seconds between the flash and the thunder — every 5 seconds ≈ 1 mile.",
    "Some of Dominica's heaviest rainfall happens without hurricanes, from tropical waves or stalled low-pressure systems."
) 